services:
  backend:
    build: ./backend
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
