[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easy-nlp-translate>=0.3.0",
    "fastapi>=0.115.12",
    "faster-whisper>=1.1.1",
    "ffmpeg>=1.4",
]
