name: Python Code Quality
on:
  pull_request:
    branches:
      - main
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: |
          cd bff_api
          uv lock
          uv run pytest -v --durations=0
      - run: |
          cd inference
          uv lock
          uv run pytest -v --durations=0
      - run: |
          cd metrics
          uv lock
          uv run pytest -v --durations=0
